### ISSUE TITLE
Feature Request : Show hostname alongside ip address 

### ISSUE THREAD

**Issue by ericnyamu1** [czarnaowca/MasscanResultsParser#1]
Hi,
This masscan parser is very helpful but instead of showing ip address only whynot resolve it and show hostname alongside it.Like this 

192.168.0.1 (hostname)
                port: 53/tcp is open
                port: 80/tcp is open
192.168.0.12 (hostname)
               port: 8080/tcp is open
               port: 9989/tcp is open
192.168.0.123 (hostname)
	port: 3389/tcp is open

It would be very helpful especially when scanning many ips.

**Comment by czarnaowca** [comment]
Hi,
Thank you for your opinion. Good to hear that this tool is useful for someone else to. I'll implement this feature in next week.

**Comment by czarnaowca** [comment]
Hi,

I looked at masscan documentation and noticed that the masscan doesn't resolve DNS by default. So we have an issue. When you need parse results with internal IPs (as you mentioned above) on another computer which works in different network it can't be done. Also if you have the same address but physically it is a different network.
